title: All About Kids Research
description: sparking conversations about paediatric research

url: http://allaboutkidsresearch.ca
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5


navigation:


social:
   twitter: aakrblog

google_analytics: "UA-72891427-1"
