title: All About Kids Research
description: sparking conversations about paediatric research

url: http://SKaakr.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Guest Writers
   url: /guests
 - title: Contribute
   url: /contribute
 - title: Contact
   url: /contact

social:
   twitter: aakrblog
   email: allaboutkidsresearch@gmail.com
