title: All About Kids Research
description: Sparking conversations about paediatric research. A project by Stephanie Cheung and Karolina Urban.

url: http://stephaniecheung.ca/allaboutkidsresearch
baseurl: "http://stephaniecheung.ca/allaboutkidsresearch"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-feed
paginate: 5


navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contribute
   url: /contribute
 - title: Contact
   url: /contact
 - title: Archive
   url: /archive

social:
   twitter: aakresearch

google_analytics: "UA-72891427-1"
