title: All About Kids Research
description: sparking conversations about paediatric research

url: https://skaakr.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5


navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Guest Writers
   url: /guests
 - title: Contribute
   url: /contribute
 - title: Contact
   url: /contact
 - title: Archive
   url: /archive

social:
   twitter: aakrblog
